version: '3.8'

services:

  jira:
    environment:
    - ATL_TOMCAT_SECURE=true
    - ATL_TOMCAT_SCHEME=https
    - ATL_PROXY_PORT=443

  nginx:
    # FIXME look sick, need some kind of magic
    volumes:
    - ./nginx/conf.d/secure.conf.template:/etc/nginx/templates/secure.conf.template
    # we might use provided cert stuffs
    - ./certs/:/etc/nginx/certs/
    ports:
    - "443:443"

