version: '3.8'

volumes:
  pg-data: {}
  jira-data: {}

x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: 100m
    max-file: "15"

services:

  postgres:
    container_name: postgres
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: jira
      POSTGRES_DB: jira
      POSTGRES_PASSWORD: ocsg1234
    volumes:
     - pg-data:/var/lib/postgresql/data/
    logging: *default-logging

  jira:
    container_name: jira
    image: atlassian/jira-software:8.11
    restart: always
    environment:
     # reverse proxy config, will be updated when deploy into other platforms
     - ATL_PROXY_NAME=${DOMAIN_NAME}
     - ATL_PROXY_PORT=80
     - ATL_TOMCAT_SCHEME=http
     # DB config
     - ATL_JDBC_URL=jdbc:postgresql://postgres:5432/jira
     - ATL_JDBC_USER=jira
     - ATL_JDBC_PASSWORD=ocsg1234
     - ATL_DB_DRIVER=org.postgresql.Driver
     - ATL_DB_TYPE=postgres72
     # let's crack it :)
     - JVM_SUPPORT_RECOMMENDED_ARGS=-javaagent:/atlassian-agent.jar
    volumes:
     - ./atlassian-agent.jar:/atlassian-agent.jar
     - jira-data:/var/atlassian/application-data/jira/
    depends_on:
     - postgres
    logging: *default-logging

