version: '3.8'

services:

  postgres:
    image: postgres:11
    restart: always
    environment:
#      POSTGRES_USER: postgres
#      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: ocsg1234
#    volumes:
# for continously restarting while testing, no need volumes
#      - pg-data:/var/lib/postgresql/data
#      - jira-data:/var/atlassian/application-data/jira
    ports:
      - 5432:5432

  jira:
    container_name: jira 
    # current latest version is 8.11
    image: atlassian/jira-software:8.1
    environment:
     # will be updated when deploy into aws
     - ATL_PROXY_NAME=jira.internal
     - ATL_PROXY_PORT=80
     - ATL_TOMCAT_SCHEME=http
     - ATL_JDBC_URL=jdbc:postgresql://postgres:5432/postgres
     - ATL_JDBC_USER=postgres
     - ATL_JDBC_PASSWORD=ocsg1234
     - ATL_DB_DRIVER=org.postgresql.Driver
     - ATL_DB_TYPE=postgres72

  nginx: 
    container_name: nginx 
    image: nginx:latest 
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf 
    depends_on: 
     - jira 
    ports: 
     - "80:80" 
    networks: 
      default: 
        aliases:
         - jira.internal

# volumes:
#   pg-data:
#   jira-data:

