version: '3.8'

services:

  postgres:
    container_name: postgres
    image: postgres:11
    restart: always
    environment:
      POSTGRES_USER: jira
      POSTGRES_DB: jira
      POSTGRES_PASSWORD: ocsg1234

  jira:
    container_name: jira
    # current latest version is 8.11
    image: atlassian/jira-software:8.11
    restart: always
    environment:
     # reverse proxy config, will be updated when deploy into aws
     - ATL_PROXY_NAME=nginx
     - ATL_PROXY_PORT=80
     - ATL_TOMCAT_SCHEME=http
     # DB config
     - ATL_JDBC_URL=jdbc:postgresql://postgres:5432/jira
     - ATL_JDBC_USER=jira
     - ATL_JDBC_PASSWORD=ocsg1234
     - ATL_DB_DRIVER=org.postgresql.Driver
     - ATL_DB_TYPE=postgres72
     # let's crack it :)
     - JVM_SUPPORT_RECOMMENDED_ARGS=-javaagent:/atlassian-agent.jar
    volumes:
     - ./atlassian-agent.jar:/atlassian-agent.jar
    depends_on:
     - postgres

  nginx:
    container_name: nginx
    image: nginx:latest
    restart: always
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
     - jira
    ports:
     - "80:80"

